Dev
IvanSavkivIgorovych/JS pull request #2
Opened 2021-05-24 15:48 UTC by IvanSavkivIgorovych

Homework 24 
I don't have much tome for task#10 or I'm am fool)))

2021-05-24 17:24 UTC, IvanSavkivIgorovych commented
Homework#25

2021-05-24 19:51 UTC, antkl requested changes

2021-05-24 19:51 UTC, antkl commented on lesson24/js/task_1.js
> +    );
використовуй тернарні оператори, коли треба віддати значення, а в іншому випадку краще `if ... else`
https://learn.javascript.ru/ifelse#netraditsionnoe-ispolzovanie

2021-05-24 19:51 UTC, antkl commented on lesson24/js/task_1.js
> +minNumber >= maxNumber
краще відразу перевіряти введені дані, а потім виконувати обчислення

2021-05-24 19:51 UTC, antkl commented on lesson24/js/task_10.js
> +} while (finishGame !== "=");
працює неправильно 😢  спробуй ввести декілька раз `>`,
спочатку видає 75, потім 18, 27, 6 ...
подумай, як можна переробити, щоб тільки раз за ітерацію рахувати N і раз використовувати `prompt()`
_(треба ввести дві змінні: **start** і **end**)_

2021-05-24 19:51 UTC, antkl commented on lesson24/js/task_2.js
> +}
можна ще піти ззаду наперед, щоб було менше ітерацій
```js
for (let j = minOfNumbers;  j >= 1;  j--) {
  if (Math.abs(firstNumber) % j === 0 && Math.abs(secondNumber) % j === 0) {
    commonDivisor = j;
    break;
  }
}
```

2021-05-24 19:51 UTC, antkl commented on lesson24/js/task_6.js
> +  operator = prompt("Enter the operator (+, -, *, /, or ^):");
```suggestion
  const num_1 = +prompt("Enter the first number:");
  const num_2 = +prompt("Enter the second number:");
  const operator = prompt("Enter the operator (+, -, *, /, or ^):");
  let result = null;
```

2021-05-24 19:51 UTC, antkl commented on lesson24/js/task_8.js
> +  }
а `switch ... case`?=)

2021-05-24 19:51 UTC, antkl commented on lesson24/js/task_8.js
> +    message = "Monday. ";
краще в `message` просто Monday

2021-05-24 19:51 UTC, antkl commented on lesson24/js/task_8.js
> +  yesOrNo = confirm(`${message}Do you want to see the next day of the week???`);
а тут вже робити крапку і пробіл
```suggestion
  yesOrNo = confirm(`${message}. Do you want to see the next day of the week???`);
```

2021-05-24 19:51 UTC, antkl commented on lesson25/js/task_4.js
> +}
👍

2021-05-24 19:51 UTC, antkl commented on lesson25/js/task_6.js
> +  }
можна просто
```suggestion
  return sumOfDivisors === x;
```

2021-05-24 19:51 UTC, antkl commented on lesson25/js/task_6.js
> +  }
можна переписати і використати функцію з попереднього завдання, тільки щоб вона повертала `boolean`

2021-05-24 19:51 UTC, antkl commented on lesson25/js/task_5.js
> +  }
функція в ідеалі виконує одну дію
тут же вона не тільки перевіряє чи ідеальне число, чи ні, а ще й виводить
краще, щоб вона просто повертала `boolean`, а потім вже хеш виводь в консоль, хочеш ще десь=)

2021-05-24 19:51 UTC, antkl commented on lesson25/js/task_7.js
> +}
```js
// можна винести в окрему функцію
function formatTimeUnit(value) {
  return value.toString().padStart(2, "0");
}

// .. функція приймає числа, тому й дефолтні значення - числа
// і може краще назвати formatTime
function formatTime(hours, minutes = 0, seconds = 0) {
  // повертаємо значення, щоб можна було використати
  return (
    formatTimeUnit(hours) +
    ":" +
    formatTimeUnit(minutes) +
    ":" +
    formatTimeUnit(seconds)
  );
}
```

2021-05-24 19:51 UTC, antkl commented on lesson25/js/task_9.js
> +  );
```suggestion
  return formatTime(hour, minute, second)
```

2021-05-24 19:51 UTC, antkl commented on lesson25/js/task_10.js
> +  second2 = "00"
```suggestion
  hour1,
  minute1 = 0,
  second1 = 0,
  hour2,
  minute2 = 0,
  second2 = 0
```

2021-05-24 19:51 UTC, antkl commented on lesson25/js/task_10.js
> +}
використай з попередніх завдань

2021-05-25 04:20 UTC, IvanSavkivIgorovych commented on lesson24/js/task_1.js
> +    );
Зрозумів, не знав. Виправив.

2021-05-25 04:21 UTC, IvanSavkivIgorovych commented on lesson24/js/task_10.js
> +} while (finishGame !== "=");
Я знаю, якось не зміг додуматися, як це правильно зробити, на листку зробивз математичної точки зору. А тут прийдеться подумати...

2021-05-25 04:22 UTC, IvanSavkivIgorovych commented on lesson24/js/task_2.js
> +}
Точняк))))

2021-05-25 04:26 UTC, IvanSavkivIgorovych commented on lesson24/js/task_6.js
> +  operator = prompt("Enter the operator (+, -, *, /, or ^):");
Провтикав))

2021-05-25 04:28 UTC, IvanSavkivIgorovych commented on lesson24/js/task_8.js
> +  }
Перше робив свічом, але ж там умову не можна писати

2021-05-25 04:29 UTC, IvanSavkivIgorovych commented on lesson24/js/task_8.js
> +  }
dayOfWeek % 7 === 0
Тут я ж робив через остачу від ділення, щоб воно було зациклено. Подумаю)

2021-05-25 04:34 UTC, IvanSavkivIgorovych commented on lesson25/js/task_6.js
> +  }
Можна)

2021-05-25 04:36 UTC, IvanSavkivIgorovych commented on lesson25/js/task_5.js
> +  }
Ок, пойняв)))

2021-05-25 04:40 UTC, IvanSavkivIgorovych commented on lesson25/js/task_7.js
> +}
Класна ідея, зменшить код)

2021-05-25 04:44 UTC, merged